### ISSUE TITLE
Showing IMDb, Trakt and TMDb links on a movie page

### ISSUE THREAD

**Issue by ronilaukkarinen** [jeherve/traktivity#182]
Sorry to bombard you with issues! I saw [here](https://jeremy.hu/show/the-expanse/) you have lots of metadata visible. How to show them on a template? I can easily dig taxonomies and stuff like that but how to get IMDb link etc. shown?

**Comment by jeherve** [comment]
> How to show them on a template?


You can check this file to see how I did it in my previous theme on my personal site, that should give you an idea:
https://github.com/jeherve/independent-jeremy/blob/a9a461b6d0a19e2f5346e6e84507873ca106c034/taxonomy-trakt_show.php

The links to outside resources are built here:

```php
// Display links to other sites.
$elsewhere = get_term_meta( $term->term_id, 'show_external_ids', true );
if ( ! empty( $elsewhere ) ) {
	printf(
		'<div class="show_links"><a href="http://www.imdb.com/title/%1$s">IMDb</a> | <a href="https://trakt.tv/shows/%2$s">Trakt</a> | <a href="https://www.themoviedb.org/tv/%3$s">TMDb</a></div><hr />',
		esc_attr( $elsewhere['imdb'] ),
		esc_attr( $elsewhere['trakt'] ),
		esc_attr( $elsewhere['tmdb'] )
	);
}
```

Hopefully this helps!
