### ISSUE TITLE
Feature request: Disable TV shows, sync only movies

### ISSUE THREAD

**Issue by ronilaukkarinen** [jeherve/traktivity#183]
As I'm building a movie review site TV shows are not really needed. Now they are mandarory. Would you consider adding an option to disable them completely that would exclude syncing them?

**Comment by jeherve** [comment]
I'm just releasing version 2.3.0 of the plugin. Once you have that version of the plugin, you'll be able to use a filter to customize the data you fetch from Trakt.tv. In the example below, we fetch only movie activity:

```php
/**
 * Filter the URL used to fetch activity data from Trakt.
 *
 * @param string $query_url Query URL.
 * @param string $api_url   API URL. Default to TRAKTIVITY__API_URL.
 * @param string $username  Trakt username.
 */
function jeherve_traktivity_only_fetch_movies( $query_url, $api_url, $username ) {
	$query_url = sprintf(
		'%1$s/users/%2$s/history/movies/?extended=full',
		$api_url,
		$username
	);

	return $query_url;
}
add_filter( 'traktivity_get_activity_url', 'jeherve_traktivity_only_fetch_movies', 10, 3 );
```

**Comment by ronilaukkarinen** [comment]
Awesome! Thank you so much. ❤️
Will test on upcoming weekend.
