### ISSUE TITLE
"Invalid API key or unapproved app" on 2.3.0

### ISSUE THREAD

**Issue by ronilaukkarinen** [jeherve/traktivity#184]
Removed posts and options from the db, reinstalled by removing plugin folder and adding and activating again via wp-admin. Even tried to create a new app but always getting "Invalid API key or unapproved app" in briefing. Nothing on Console. What's wrong?

**Comment by jeherve** [comment]
Can you doublecheck that your Trakt.tv API key is correct? That response comes from the Trakt.tv API.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
